name: "Build AnyBlob"
description: "Build AnyBlob using either clang or gcc"
inputs:
    clang-toolchain:
        required: false
        description: "Build with clang and use libcxx as the standard library"
        default: false
    uring-compat:
        required: false
        description: "Build without uring"
        default: 0

runs:
    using: "composite"
    steps:
      # CMake configuration option 1 - GCC toolchain
      - name: Configure CMake
        if: ${{ inputs.clang-toolchain == 'false' }}
        run: |
          cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DANYBLOB_URING_COMPAT=${{ inputs.uring-compat }}
        shell: bash

      # CMake configuration option 2 - Clang toolchain
      - name: Configure CMake
        if: ${{ inputs.clang-toolchain == 'true' }}
        # Explicitly use clang-18. The runner comes with clang-18.
        run: |
          sudo apt install libc++-18-dev libc++abi-18-dev
          cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} \
                -DCMAKE_C_COMPILER=clang-18  \
                -DCMAKE_CXX_COMPILER=clang++-18 \
                -DANYBLOB_LIBCXX_COMPAT=1 \
                -DANYBLOB_URING_COMPAT=${{ inputs.uring-compat }}
        shell: bash

      # Build library and test binaries
      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
        shell: bash
