name: MinIO Integration Test

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - "*"

env:
  BUILD_TYPE: Debug
  # False ASAN positives for alloc_dealloc_mismatch when running with clang
  # https://github.com/llvm/llvm-project/issues/59432
  ASAN_OPTIONS: alloc_dealloc_mismatch=0

jobs:
  integration-test:
    name: Integration Tests (Clang ${{ matrix.clang-toolchain }}) (Uring Compat ${{ matrix.uring-compat }})
    # Run on ubuntu
    runs-on: ubuntu-latest
    # Use both the GCC and Clang Toolchain
    strategy:
        matrix:
            clang-toolchain: [true, false]
            uring-compat: [0, 1]

    # Define the steps
    steps:
      # Install MinIO Docker
      - name: Install MinIO Docker
        run: |
          docker run -d -p 9000:9000 --name minio \
          -e "MINIO_ACCESS_KEY=test" -e "MINIO_SECRET_KEY=testtest" \
          -v /tmp/buckets:/buckets -v /tmp/.minio:/root/.minio \
          minio/minio server /buckets

          export AWS_ACCESS_KEY_ID=test
          export AWS_SECRET_ACCESS_KEY=testtest
          export AWS_EC2_METADATA_DISABLED=true

          aws --endpoint-url http://127.0.0.1:9000/ s3 mb s3://test

      # Checkout repo
      - uses: actions/checkout@v3
        with:
          submodules: true

      # Use action to install dependencies
      - name: Install Dependencies
        uses: ./.github/actions/install-deps

      # Use action to build
      - name: Build AnyBlob
        uses: ./.github/actions/do-build
        with:
            clang-toolchain: ${{ matrix.clang-toolchain }}
            uring-compat: ${{ matrix.uring-compat }}

      # Run the integration test
      - name: Integration Test
        working-directory: ${{github.workspace}}/build
        run: |
          export AWS_S3_BUCKET=test
          export AWS_S3_REGION=us-east-1
          export AWS_S3_ENDPOINT=127.0.0.1:9000
          export AWS_S3_ACCESS_KEY=test
          export AWS_S3_SECRET_ACCESS_KEY=testtest

          ./integration
