name: Unit Test

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev

env:
  BUILD_TYPE: Debug
  # False ASAN positives for alloc_dealloc_mismatch when running with clang 
  # https://github.com/llvm/llvm-project/issues/59432
  ASAN_OPTIONS: alloc_dealloc_mismatch=0 

jobs:
  unit-test:
    name: Unit Tests (Clang ${{ matrix.clang-toolchain }})
    # Run on ubuntu
    runs-on: ubuntu-latest
    # Use both the GCC and Clang Toolchain
    strategy:
        matrix:
            clang-toolchain: [true, false]

    # Define the steps
    steps:
      # Checkout repo
      - uses: actions/checkout@v3
        with:
          submodules: true

      # Use action to install dependencies 
      - name: Install Dependencies 
        uses: ./.github/actions/install-deps

      # Use action to build 
      - name: Build AnyBlob
        uses: ./.github/actions/do-build
        with:
            clang-toolchain: ${{ matrix.clang-toolchain }}

      # Run the unit tests
      - name: Unit Test
        working-directory: ${{github.workspace}}/build
        run: ./tester
